
import type { Movie } from './types';

export const movies: Movie[] = [
  {
    id: '1',
    title: 'Dexter',
    description: 'Um especialista forense de Miami que, nas horas vagas, caça e mata outros assassinos em série.',
    genre: 'Crime',
    cast: ['Michael C. Hall', 'Jennifer Carpenter', 'David Zayas'],
    posterUrl: 'https://m.media-amazon.com/images/I/81JKXT1j0OL._AC_UF894,1000_QL80_.jpg',
    rating: 8.6,
    year: 2006,
    aiHint: 'crime drama',
  },
  {
    id: '2',
    title: 'You',
    description: 'Um jovem perigosamente charmoso e intensamente obsessivo que toma medidas extremas para se inserir na vida daqueles por quem é obcecado.',
    genre: 'Thriller',
    cast: ['Penn Badgley', 'Victoria Pedretti', 'Elizabeth Lail'],
    posterUrl: 'https://br.web.img2.acsta.net/c_310_420/pictures/18/12/31/02/49/2373131.jpg',
    rating: 7.7,
    year: 2018,
    aiHint: 'psychological thriller',
  },
  {
    id: '3',
    title: 'Outer Banks',
    description: 'Um grupo de adolescentes da Carolina do Norte embarca em uma missão para encontrar o tesouro lendário que o pai do seu líder tentou encontrar.',
    genre: 'Action',
    cast: ['Chase Stokes', 'Madelyn Cline', 'Madison Bailey'],
    posterUrl: 'https://theblazerrhs.com/wp-content/uploads/2024/12/outer-banks-season-4.jpg',
    rating: 7.6,
    year: 2020,
    aiHint: 'teen adventure',
  },
  {
    id: '4',
    title: 'The Lost Pirate Kingdom',
    description: 'Nesta série documental, os verdadeiros piratas do Caribe saqueiam violentamente as riquezas do mundo e formam uma república surpreendentemente igualitária.',
    genre: 'Documentary',
    cast: ['Sam Callis', 'Tom Padley', 'Evan Milton'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZGFjZDQ1ZGItYTEyOC00OGRiLWJiMDgtN2ExNTdjOTMwZjViXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: 6.8,
    year: 2021,
    aiHint: 'pirate documentary',
  },
  {
    id: '5',
    title: 'Peaky Blinders',
    description: 'Um épico de uma família de gângsteres ambientado na Inglaterra de 1900, centrado em uma gangue que costura lâminas de barbear nas abas de seus bonés e em seu chefe feroz, Tommy Shelby.',
    genre: 'Crime',
    cast: ['Cillian Murphy', 'Sam Neill', 'Helen McCrory'],
    posterUrl: 'https://www.crew-united.com/Media/Images/1582/1582796/1582796.entity.jpg',
    rating: 8.8,
    year: 2013,
    aiHint: 'historical crime',
  },
  {
    id: '6',
    title: 'Pulp Fiction',
    description: 'As vidas de dois assassinos de aluguel, um boxeador, a esposa de um gângster e um casal de assaltantes de lanchonete se entrelaçam em quatro contos de violência e redenção.',
    genre: 'Crime',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    posterUrl: 'https://upload.wikimedia.org/wikipedia/pt/8/82/Pulp_Fiction_cover.jpg',
    rating: 8.9,
    year: 1994,
    aiHint: 'crime film',
  },
  {
    id: '7',
    title: 'The Midnight Gospel',
    description: 'Um podcaster espacial com um simulador de multiverso defeituoso viaja por mundos psicodélicos para entrevistar os seres que vivem neles.',
    genre: 'Animation',
    cast: ['Duncan Trussell', 'Phil Hendrie', 'Drew Pinsky'],
    posterUrl: 'https://upload.wikimedia.org/wikipedia/pt/thumb/f/f0/The_Midnight_Gospel.jpg/250px-The_Midnight_Gospel.jpg',
    rating: 8.2,
    year: 2020,
    aiHint: 'adult animation',
  },
  {
    id: '8',
    title: 'Dark',
    description: 'Uma saga familiar com um toque sobrenatural, ambientada em uma cidade alemã, onde o desaparecimento de duas crianças expõe as relações entre quatro famílias.',
    genre: 'Sci-Fi',
    cast: ['Louis Hofmann', 'Karoline Eichhorn', 'Lisa Vicari'],
    posterUrl: 'https://upload.wikimedia.org/wikipedia/pt/f/f6/Dark_%28s%C3%A9rie%29.jpg',
    rating: 8.8,
    year: 2017,
    aiHint: 'mystery sci-fi',
  },
  {
    id: '9',
    title: 'Daybreak',
    description: 'O estudante desajustado Josh Wheeler procura sua namorada desaparecida Sam Dean na pós-apocalíptica Glendale, Califórnia.',
    genre: 'Comedy',
    cast: ['Colin Ford', 'Alyvia Alyn Lind', 'Sophie Simnett'],
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/47/Poster_for_Netflix_series_Daybreak.png',
    rating: 7.6,
    year: 2019,
    aiHint: 'post-apocalyptic comedy',
  },
  {
    id: '10',
    title: 'iCarly',
    description: 'Uma garota chamada Carly apresenta seu próprio programa na web, iCarly, que se torna uma sensação online.',
    genre: 'Comedy',
    cast: ['Miranda Cosgrove', 'Jerry Trainor', 'Jennette McCurdy'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BY2JlM2JiNmQtNTdhNy00MDljLThjNDQtZDExNWI0NTNhMjVlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: 6.7,
    year: 2007,
    aiHint: 'teen sitcom',
  },
  {
    id: '11',
    title: 'Ozark',
    description: 'Um consultor financeiro arrasta sua família de Chicago para os Ozarks do Missouri, onde ele deve lavar 500 milhões de dólares em cinco anos para apaziguar um chefe do tráfico.',
    genre: 'Crime',
    cast: ['Jason Bateman', 'Laura Linney', 'Julia Garner'],
    posterUrl: 'https://resizing.flixster.com/WpM6gj21EIoYoyKLcbhkMp02KbY=/206x305/v2/https://resizing.flixster.com/3ko6zO6791p1QPOXHUI2eCwmHXQ=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvMDIyOTBmN2QtMzM0Yi00ODUxLWE0MWYtMmViYWJiOGViZjRkLmpwZw==',
    rating: 8.4,
    year: 2017,
    aiHint: 'crime thriller',
  },
  {
    id: '12',
    title: 'Como Vender Drogas Online (Rápido)',
    description: 'Para reconquistar sua ex-namorada, um adolescente nerd começa a vender ecstasy online de seu quarto e se torna um dos maiores traficantes da Europa.',
    genre: 'Comedy',
    cast: ['Maximilian Mundt', 'Danilo Kamperidis', 'Lena Klenke'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaF-ubV-aP_3EjCWoIrCoLnRUhDlJsicdHuclKwrsy-IJMMztY',
    rating: 7.9,
    year: 2019,
    aiHint: 'german comedy',
  },
  {
    id: '13',
    title: 'Big Mouth',
    description: 'Amigos adolescentes descobrem que suas vidas foram viradas de cabeça para baixo pelas maravilhas e horrores da puberdade nesta comédia de animação ousada dos amigos Nick Kroll e Andrew Goldberg.',
    genre: 'Animation',
    cast: ['Nick Kroll', 'John Mulaney', 'Jessi Klein'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTU0YjUyNDctYmM0OC00OWU5LWJmNTMtODY5Njc4MzVlMWE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: 8.0,
    year: 2017,
    aiHint: 'adult animation',
  },
  {
    id: '14',
    title: '(Des)encanto',
    description: 'As desventuras da princesa Bean no reino medieval em ruínas de Dreamland.',
    genre: 'Animation',
    cast: ['Abbi Jacobson', 'Eric André', 'Nat Faxon'],
    posterUrl: 'https://marquettemessenger.com/wp-content/uploads/2018/09/p15553420_b_v8_ac-600x900.jpg',
    rating: 7.2,
    year: 2018,
    aiHint: 'fantasy animation',
  },
  {
    id: '15',
    title: 'BoJack Horseman',
    description: 'Conheça o cavalo de sitcom mais amado dos anos 90 - 20 anos depois. Ele é um rabugento com um coração de... não exatamente ouro... mas algo parecido com ouro. Cobre?',
    genre: 'Animation',
    cast: ['Will Arnett', 'Amy Sedaris', 'Alison Brie'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZmMwMDlkNTEtMmQzZS00ODQ0LWJlZmItOTgwYWMwZGM4MzFiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: 8.7,
    year: 2014,
    aiHint: 'adult animation',
  },
  {
    id: '16',
    title: 'The Irrational',
    description: 'Um professor de renome mundial de ciência comportamental empresta sua experiência a uma série de casos de alto risco envolvendo governos, aplicação da lei e corporações.',
    genre: 'Drama',
    cast: ['Jesse L. Martin', 'Maahra Hill', 'Travina Springer'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRjlgYXLE83x-Mg2cfmzZdSv9Ynyngr-v6EDz1Wswlb2UngUc--',
    rating: 7.2,
    year: 2023,
    aiHint: 'procedural drama',
  },
  {
    id: '17',
    title: 'The Flash',
    description: 'Após ser atingido por um raio, Barry Allen acorda de seu coma para descobrir que recebeu o poder da supervelocidade, tornando-se o Flash e combatendo o crime em Central City.',
    genre: 'Action',
    cast: ['Grant Gustin', 'Candice Patton', 'Danielle Panabaker'],
    posterUrl: 'https://www.imdb.com/title/tt3107288/mediaviewer/rm2718842113/',
    rating: 7.6,
    year: 2014,
    aiHint: 'superhero action',
  },
  {
    id: '18',
    title: 'Round Six (Squid Game)',
    description: 'Centenas de jogadores com problemas financeiros aceitam um estranho convite para competir em jogos infantis. Dentro, um prêmio tentador os aguarda com apostas mortais.',
    genre: 'Thriller',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon'],
    posterUrl: 'https://br.web.img3.acsta.net/img/88/2d/882d8fcd800fe37be85af13ee0c38556.jpg',
    rating: 8.1,
    year: 2021,
    aiHint: 'survival drama',
  },
  {
    id: '19',
    title: 'Breaking Bad',
    description: 'Um professor de química do ensino médio diagnosticado com câncer de pulmão inoperável se volta para a fabricação e venda de metanfetamina para garantir o futuro de sua família.',
    genre: 'Crime',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg',
    rating: 9.5,
    year: 2008,
    aiHint: 'crime drama',
  },
  {
    id: '20',
    title: 'Stranger Things',
    description: 'Quando um garoto desaparece, sua mãe, um chefe de polícia e seus amigos devem enfrentar forças sobrenaturais aterrorizantes para recuperá-lo.',
    genre: 'Sci-Fi',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    posterUrl: 'https://resizing.flixster.com/0xxuABVVuzJrUT130WFHKE-irEg=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vNzUyMTFhOTktZTU4Ni00ODkyLWJlYjQtZTgxYTllZmU2OGM0LmpwZw==',
    rating: 8.7,
    year: 2016,
    aiHint: 'supernatural horror',
  },
  {
    id: '21',
    title: 'The Witcher',
    description: 'Geralt de Rívia, um caçador de monstros solitário, luta para encontrar seu lugar em um mundo onde as pessoas frequentemente se mostram mais perversas do que as feras.',
    genre: 'Fantasy',
    cast: ['Henry Cavill', 'Anya Chalotra', 'Freya Allan'],
    posterUrl: 'https://br.web.img3.acsta.net/pictures/19/11/29/17/57/5161763.jpg',
    rating: 8.2,
    year: 2019,
    aiHint: 'fantasy series',
  },
  {
    id: '22',
    title: 'Os Donos do Jogo (Players)',
    description: 'Uma equipe fictícia de e-sports de League of Legends, liderada por um jogador veterano e um novo prodígio, tenta vencer seu primeiro campeonato.',
    genre: 'Comedy',
    cast: ['Misha Brooks', 'Da\'Jour Jones', 'Ely Henry'],
    posterUrl: 'https://br.web.img3.acsta.net/img/9a/ed/9aed09610f84de0e13589af031f11089.jpg',
    rating: 8.3,
    year: 2022,
    aiHint: 'esports comedy',
  },
  {
    id: '23',
    title: 'Bridgerton',
    description: 'Riqueza, luxúria e traição ambientadas na era da Regência na Inglaterra, vistas pelos olhos da poderosa família Bridgerton.',
    genre: 'Romance',
    cast: ['Phoebe Dynevor', 'Regé-Jean Page', 'Nicola Coughlan'],
    posterUrl: 'https://resizing.flixster.com/138uPFHeLeB8oGxrkUdCSHQDAsE=/fit-in/705x460/v2/https://resizing.flixster.com/I_zHuKCiZSwuXD7jSZ3WHpnVngo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvZjU3NzI1NTktNDBhNC00YTc4LThkZGYtODAxMTgwZmM3ZDlmLmpwZw==',
    rating: 7.3,
    year: 2020,
    aiHint: 'period romance',
  },
  {
    id: '24',
    title: 'Bandidagem (Gangs of Galicia)',
    description: 'Quando o assassinato de seu pai revela uma vida dupla, uma advogada busca vingança se infiltrando em um cartel de drogas galego e se aproximando de seu líder.',
    genre: 'Crime',
    cast: ['Clara Lago', 'Tamar Novas', 'Xosé Antonio Touriñán'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWhRZawPRGIc6lo0jImRr1c722JcHYmHIEQKjThj4nqo33HZ6-',
    rating: 6.4,
    year: 2024,
    aiHint: 'crime drama',
  },
  {
    id: '25',
    title: 'The Umbrella Academy',
    description: 'Uma família de ex-heróis infantis, agora separados, deve se reunir para continuar a proteger o mundo.',
    genre: 'Action',
    cast: ['Elliot Page', 'Tom Hopper', 'David Castañeda'],
    posterUrl: 'https://images.ctfassets.net/4cd45et68cgf/5ubPW3UKcPpDwThgu4X01O/7556b6756fcb6168b11caab885117e24/PT-BR_CARAMELO_Main-Key-Art_Dupla_Vertical_4x5_sRGB_PRE.jpg?w=2000',
    rating: 8.0,
    year: 2019,
    aiHint: 'superhero action',
  },
  {
    id: '26',
    title: 'Cobra Kai',
    description: 'Décadas após a luta no Torneio de Karatê All Valley de 1984, um Daniel LaRusso e um Johnny Lawrence de meia-idade se encontram novamente como rivais de artes marciais.',
    genre: 'Action',
    cast: ['Ralph Macchio', 'William Zabka', 'Xolo Maridueña'],
    posterUrl: 'https://br.web.img2.acsta.net/pictures/21/01/04/12/12/0170975.jpg',
    rating: 8.6,
    year: 2018,
    aiHint: 'karate action',
  },
  {
    id: '27',
    title: 'Sex Education',
    description: 'Um adolescente com uma mãe terapeuta sexual se junta a uma colega de classe para montar uma clínica de terapia sexual clandestina na escola.',
    genre: 'Comedy',
    cast: ['Asa Butterfield', 'Gillian Anderson', 'Ncuti Gatwa'],
    posterUrl: 'https://idris.com.br/dev/wp-content/uploads/2019/01/poltrona-Sex-education-poster.jpg',
    rating: 8.3,
    year: 2019,
    aiHint: 'teen comedy',
  },
  {
    id: '28',
    title: 'Henry Danger',
    description: 'Henry Hart, de 13 anos, consegue um emprego de meio período como Kid Danger, o aprendiz de super-herói do Capitão Man.',
    genre: 'Comedy',
    cast: ['Jace Norman', 'Cooper Barnes', 'Riele Downs'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8V_5-Q5_r_o-e-gJ_p-iH-e-f_b-K_yA&s',
    rating: 6.0,
    year: 2014,
    aiHint: 'kids comedy',
  },
  {
    id: '29',
    title: 'One Piece (Live Action)',
    description: 'Em um mundo de navegantes, um jovem capitão pirata parte com sua tripulação para obter o título de Rei dos Piratas e descobrir o tesouro mítico conhecido como \'One Piece\'.',
    genre: 'Action',
    cast: ['Iñaki Godoy', 'Mackenyu', 'Emily Rudd'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1Xv9Q3r-vY-Z_y_x-gJ_wI7F_q_K_kY_Q&s',
    rating: 8.4,
    year: 2023,
    aiHint: 'adventure fantasy',
  },
  {
    id: '30',
    title: 'Caramelo (Caramel)',
    description: 'Em um salão de beleza em Beirute, as vidas de cinco mulheres se cruzam. Cada uma tem sua própria história, problemas e segredos.',
    genre: 'Drama',
    cast: ['Nadine Labaki', 'Yasmine Al Massri', 'Joanna Moukarzel'],
    posterUrl: 'https://images.ctfassets.net/4cd45et68cgf/5ubPW3UKcPpDwThgu4X01O/7556b6756fcb6168b11caab885117e24/PT-BR_CARAMELO_Main-Key-Art_Dupla_Vertical_4x5_sRGB_PRE.jpg?w=2000',
    rating: 7.1,
    year: 2007,
    aiHint: 'lebanese drama',
  },
  {
    id: '31',
    title: 'Lupin',
    description: 'Inspirado nas aventuras de Arsène Lupin, o ladrão de casaca Assane Diop busca vingar seu pai por uma injustiça infligida por uma família rica.',
    genre: 'Crime',
    cast: ['Omar Sy', 'Ludivine Sagnier', 'Clotilde Hesme'],
    posterUrl: 'https://resizing.flixster.com/i6Tzks6-0MJnC7fD7nrQx4pr9Rc=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vMmJkNzExNTItMWM0MS00ODBjLWJkNGMtMTIwMmI4YTc3YTg3LmpwZw==',
    rating: 7.5,
    year: 2021,
    aiHint: 'heist thriller',
  },
  {
    id: '32',
    title: 'Good Girls',
    description: 'Três mães de subúrbio se encontram em circunstâncias desesperadoras e decidem parar de jogar pelo seguro e arriscar tudo para retomar seu poder.',
    genre: 'Comedy',
    cast: ['Christina Hendricks', 'Retta', 'Mae Whitman'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_p-Y-h_s_1PzG8-P4y8gH8z_Y4f8qL-Q&s',
    rating: 7.8,
    year: 2018,
    aiHint: 'crime comedy',
  },
  {
    id: '33',
    title: 'Wandinha (Wednesday)',
    description: 'Enquanto estuda na Academia Nevermore, Wandinha Addams tenta dominar sua habilidade psíquica emergente, frustrar uma onda de assassinatos monstruosos e resolver o mistério sobrenatural que envolveu seus pais há 25 anos.',
    genre: 'Comedy',
    cast: ['Jenna Ortega', 'Gwendoline Christie', 'Riki Lindhome'],
    posterUrl: 'https://image.tmdb.org/t/p/original/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
    rating: 8.2,
    year: 2022,
    aiHint: 'dark comedy',
  },
  {
    id: '34',
    title: 'Ponto Cego (Blindspot)',
    description: 'Uma mulher sem memórias de seu passado é encontrada nua na Times Square com o corpo totalmente coberto por tatuagens complexas.',
    genre: 'Action',
    cast: ['Sullivan Stapleton', 'Jaimie Alexander', 'Rob Brown'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb9u-h_s_1PzG8-P4y8gH8z_Y4f8qL-Q&s',
    rating: 7.3,
    year: 2015,
    aiHint: 'crime mystery',
  },
  {
    id: '35',
    title: 'The Thundermans',
    description: 'Uma família de super-heróis tenta viver uma vida normal, mas seus poderes atrapalham.',
    genre: 'Comedy',
    cast: ['Kira Kosarin', 'Jack Griffo', 'Addison Riecke'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6-E32T9-8djx2iGvA93x0sTWM-S8-kG1nQ&s',
    rating: 6.2,
    year: 2013,
    aiHint: 'kids comedy',
  },
  {
    id: '36',
    title: 'Criando Dion (Raising Dion)',
    description: 'Uma mãe solteira viúva descobre que seu filho tem superpoderes e tenta descobrir como criá-lo com segurança e responsabilidade.',
    genre: 'Sci-Fi',
    cast: ['Alisha Wainwright', 'Ja\'Siah Young', 'Jason Ritter'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4gR3B-8Y-6J_iA8Hw_zD_yQ-J_Zz5yQ_uQ&s',
    rating: 7.2,
    year: 2019,
    aiHint: 'superhero drama',
  },
  {
    id: '37',
    title: 'Lucifer',
    description: 'Lucifer Morningstar decidiu que já se cansou de ser o servo obediente no Inferno e decide passar um tempo na Terra para entender melhor a humanidade.',
    genre: 'Fantasy',
    cast: ['Tom Ellis', 'Lauren German', 'Kevin Alejandro'],
    posterUrl: 'https://image.tmdb.org/t/p/original/ekZobS8isE6mA53RAiGDG93hBxL.jpg',
    rating: 8.1,
    year: 2016,
    aiHint: 'urban fantasy',
  },
  {
    id: '38',
    title: 'Sintonia',
    description: 'Três adolescentes que vivem na mesma favela de São Paulo perseguem seus sonhos enquanto mantêm a amizade em um mundo de música, drogas e religião.',
    genre: 'Drama',
    cast: ['Jottapê', 'Bruna Mascarenhas', 'Christian Malheiros'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1Xv9Q3r-vY-Z_y_x-gJ_wI7F_q_K_kY_Q&s',
    rating: 6.9,
    year: 2019,
    aiHint: 'brazilian drama',
  },
  {
    id: '39',
    title: 'Viagem 2: A Ilha Misteriosa (Journey 2: The Mysterious Island)',
    description: 'Sean Anderson se junta ao marido de sua mãe em uma missão para encontrar seu avô, que se acredita estar desaparecido em uma ilha mítica.',
    genre: 'Action',
    cast: ['Dwayne Johnson', 'Josh Hutcherson', 'Vanessa Hudgens'],
    posterUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSlpPU5wgtEAMIdbM3J6eQPdWuNRpnaZscjuCQiJeam_5EXB_yi',
    rating: 5.7,
    year: 2012,
    aiHint: 'adventure comedy',
  },
];

    