
import type { Movie } from './types';

export const movies: Movie[] = [
  {
    id: '1',
    title: 'Dexter',
    description: 'A Miami forensics expert moonlights as a serial killer of other serial killers.',
    genre: 'Crime',
    cast: ['Michael C. Hall', 'Jennifer Carpenter', 'David Zayas'],
    posterUrl: 'https://m.media-amazon.com/images/I/81JKXT1j0OL._UF1000,1000_QL80_.jpg',
    rating: 8.6,
    year: 2006,
    aiHint: 'crime drama',
  },
  {
    id: '2',
    title: 'You',
    description: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    genre: 'Action',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    posterUrl: 'https://br.web.img3.acsta.net/pictures/18/12/31/02/49/2373131.jpg',
    rating: 8.7,
    year: 1999,
    aiHint: 'cyberpunk action',
  },
  {
    id: '3',
    title: 'Outer Banks',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    genre: 'Sci-Fi',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    posterUrl: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTzg_eguqZMhQ1vdABQh0Zj6FmtSIktXNpL1kRKlIlNUWXcLgN1',
    rating: 8.6,
    year: 2014,
    aiHint: 'space exploration',
  },
  {
    id: '4',
    title: 'La Casa de Papel',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    genre: 'Thriller',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    posterUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRH78sjPMFTyIJE1M0s6T3bnszPjIfLmHkV4QqgvwLvYZIgJL_s',
    rating: 8.6,
    year: 2019,
    aiHint: 'social thriller',
  },
  {
    id: '5',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    genre: 'Fantasy',
    cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcShwsh5DzMU6LwB72i0tI4RfVWmZXmfEiMfS-fpyGTsTJJvfhC4',
    rating: 8.8,
    year: 2001,
    aiHint: 'epic fantasy',
  },
  {
    id: '6',
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    genre: 'Crime',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
    rating: 8.9,
    year: 1994,
    aiHint: 'crime film',
  },
  {
    id: '7',
    title: 'Forrest Gump',
    description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
    genre: 'Drama',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    posterUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSOBbTE4n05v0bfz6rtuH67N3JGyWUYdh77lEi_oLZC4mPvqDPh',
    rating: 8.8,
    year: 1994,
    aiHint: 'life story',
  },
  {
    id: '8',
    title: 'Dark',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    genre: 'Action',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    posterUrl: 'https://upload.wikimedia.org/wikipedia/pt/thumb/f/f6/Dark_%28s%C3%A9rie%29.jpg/250px-Dark_%28s%C3%A9rie%29.jpg',
    rating: 9.0,
    year: 2008,
    aiHint: 'superhero noir',
  },
  {
    id: '9',
    title: 'Stranger Things',
    description: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
    genre: 'Sci-Fi',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR7RuFG1xNFUAjqIZMhhA5idmeXbLaNP9C5HbtrMaTGHiJa8H-',
    rating: 8.7,
    year: 2016,
    aiHint: 'supernatural horror',
  },
  {
    id: '10',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    genre: 'Crime',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSRQA5PMd_tejZuhUxk0S5JW7IWTmdKignL9gNsgZ_lHdt-IHrj',
    rating: 9.5,
    year: 2008,
    aiHint: 'crime drama',
  },
  {
    id: '11',
    title: 'Game of Thrones',
    description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    genre: 'Fantasy',
    cast: ['Emilia Clarke', 'Kit Harington', 'Peter Dinklage'],
    posterUrl: 'https://resizing.flixster.com/3ko6zO6791p1QPOXHUI2eCwmHXQ=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvMDIyOTBmN2QtMzM0Yi00ODUxLWE0MWYtMmViYWJiOGViZjRkLmpwZw==',
    rating: 9.2,
    year: 2011,
    aiHint: 'political fantasy',
  },
  {
    id: '12',
    title: 'The Office',
    description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    genre: 'Comedy',
    cast: ['Steve Carell', 'Rainn Wilson', 'John Krasinski'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaF-ubV-aP_3EjCWoIrCoLnRUhDlJsicdHuclKwrsy-IJMMztY',
    rating: 8.9,
    year: 2005,
    aiHint: 'workplace comedy',
  },
   {
    id: '13',
    title: 'Blade Runner 2049',
    description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
    genre: 'Sci-Fi',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST3dCSPLwz49qUGzsQlZAbDmOFuSAF_3e5uH-gvonfysREq7z0',
    rating: 8.0,
    year: 2017,
    aiHint: 'dystopian future'
  },
  {
    id: '14',
    title: 'Mad Max: Fury Road',
    description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    genre: 'Action',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH11eywQ4X9R_4Ucg1GAl4hz2zBM6WicS42tU3-ylALKQ9lxei',
    rating: 8.1,
    year: 2015,
    aiHint: 'post-apocalyptic action'
  },
  {
    id: '15',
    title: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    genre: 'Animation',
    cast: ['Daveigh Chase', 'Suzanne Pleshette', 'Miyu Irino'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRLMyA1BUde7-xBNDGkJRyHGVI1ITpVAuk7rZMYWLwOccEcGnuQ',
    rating: 8.6,
    year: 2001,
    aiHint: 'animated fantasy'
  },
  {
    id: '16',
    title: 'The Grand Budapest Hotel',
    description: 'The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.',
    genre: 'Comedy',
    cast: ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRjlgYXLE83x-Mg2cfmzZdSv9Ynyngr-v6EDz1Wswlb2UngUc--',
    rating: 8.1,
    year: 2014,
    aiHint: 'quirky comedy'
  },
  {
    id: '17',
    title: 'Black Mirror',
    description: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.',
    genre: 'Sci-Fi',
    cast: ['Jesse Plemons', 'Cristin Milioti', 'Jimmi Simpson'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjU0ZjZhNDQtMDhkYi00OWQyLWE3NGYtNzBlY2VmM2I4ZDg5XkEyXkFqcGc@._V1_.jpg',
    rating: 8.8,
    year: 2011,
    aiHint: 'tech anthology'
  },
  {
    id: '18',
    title: 'Fleabag',
    description: 'A comedy series adapted from the award-winning play about a young woman trying to cope with life in London whilst coming to terms with a recent tragedy.',
    genre: 'Comedy',
    cast: ['Phoebe Waller-Bridge', 'Sian Clifford', 'Olivia Colman'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQCCjCbok_8V1acA7zfThv2WfjilE41rTHG8VItqjZ9Uw6LP9Uy',
    rating: 8.7,
    year: 2016,
    aiHint: 'dark comedy'
  },
  {
    id: '19',
    title: 'Chernobyl',
    description: 'In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world\'s worst man-made catastrophes.',
    genre: 'Drama',
    cast: ['Jessie Buckley', 'Jared Harris', 'Stellan Skarsgård'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRcr0khV9t7IeOcVDRvC84eCW_5yidk-aWcf466252yFKNPAf5M',
    rating: 9.4,
    year: 2019,
    aiHint: 'historical drama'
  },
  {
    id: '20',
    title: 'The Social Network',
    description: 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by two brothers who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.',
    genre: 'Drama',
    cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
    posterUrl: 'https://www.europanet.com.br/image_gen/resizeimg.php?cod_produto=107066',
    rating: 7.7,
    year: 2010,
    aiHint: 'biographical drama'
  },
  {
    id: '21',
    title: 'The Witcher',
    description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
    genre: 'Fantasy',
    cast: ['Henry Cavill', 'Anya Chalotra', 'Freya Allan'],
    posterUrl: 'https://br.web.img3.acsta.net/pictures/19/11/29/17/57/5161763.jpg',
    rating: 8.2,
    year: 2019,
    aiHint: 'fantasy series',
  },
  {
    id: '22',
    title: 'Squid Game',
    description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    genre: 'Thriller',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon'],
    posterUrl: 'https://image.tmdb.org/t/p/original/dDlEWAxCgsrJ1C6Jm4p42kI82l8.jpg',
    rating: 8.1,
    year: 2021,
    aiHint: 'survival drama',
  },
  {
    id: '23',
    title: 'Bridgerton',
    description: 'Wealth, lust, and betrayal set in the backdrop of Regency era England, seen through the eyes of the powerful Bridgerton family.',
    genre: 'Romance',
    cast: ['Phoebe Dynevor', 'Regé-Jean Page', 'Nicola Coughlan'],
    posterUrl: 'https://resizing.flixster.com/138uPFHeLeB8oGxrkUdCSHQDAsE=/fit-in/705x460/v2/https://resizing.flixster.com/I_zHuKCiZSwuXD7jSZ3WHpnVngo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvZjU3NzI1NTktNDBhNC00YTc4LThkZGYtODAxMTgwZmM3ZDlmLmpwZw==',
    rating: 7.3,
    year: 2020,
    aiHint: 'period romance',
  },
  {
    id: '24',
    title: 'The Crown',
    description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
    genre: 'Drama',
    cast: ['Claire Foy', 'Olivia Colman', 'Imelda Staunton'],
    posterUrl: 'https://image.tmdb.org/t/p/original/1O4Tz2i484CU4s034n222yv30K.jpg',
    rating: 8.7,
    year: 2016,
    aiHint: 'historical drama',
  },
  {
    id: '25',
    title: 'The Queen\'s Gambit',
    description: 'Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA.',
    genre: 'Drama',
    cast: ['Anya Taylor-Joy', 'Bill Camp', 'Marielle Heller'],
    posterUrl: 'https://image.tmdb.org/t/p/original/zU0htwEjIFnkyqIdxQ2RcZFCGb.jpg',
    rating: 8.6,
    year: 2020,
    aiHint: 'chess drama',
  },
  {
    id: '26',
    title: 'Cobra Kai',
    description: 'Decades after their 1984 All Valley Karate Tournament bout, a middle-aged Daniel LaRusso and Johnny Lawrence find themselves martial-arts rivals again.',
    genre: 'Action',
    cast: ['Ralph Macchio', 'William Zabka', 'Xolo Maridueña'],
    posterUrl: 'https://image.tmdb.org/t/p/original/6alAYul43SP2f2n1y3iE3cM0aot.jpg',
    rating: 8.6,
    year: 2018,
    aiHint: 'karate action',
  },
  {
    id: '27',
    title: 'Narcos',
    description: 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.',
    genre: 'Crime',
    cast: ['Wagner Moura', 'Boyd Holbrook', 'Pedro Pascal'],
    posterUrl: 'https://image.tmdb.org/t/p/original/r7BsvAAuI2a2sXoOBaV5mB6TbsA.jpg',
    rating: 8.8,
    year: 2015,
    aiHint: 'crime biopic',
  },
  {
    id: '28',
    title: 'Ozark',
    description: 'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss.',
    genre: 'Crime',
    cast: ['Jason Bateman', 'Laura Linney', 'Julia Garner'],
    posterUrl: 'https://image.tmdb.org/t/p/original/8B4UGr03Ir02X2e5aJc4S2dliM.jpg',
    rating: 8.4,
    year: 2017,
    aiHint: 'crime thriller',
  },
  {
    id: '29',
    title: 'Sex Education',
    description: 'A teenage boy with a sex therapist mother teams up with a high school classmate to set up an underground sex therapy clinic at school.',
    genre: 'Comedy',
    cast: ['Asa Butterfield', 'Gillian Anderson', 'Ncuti Gatwa'],
    posterUrl: 'https://image.tmdb.org/t/p/original/2u1Yf3bONE3tTAkSubyD623nI7J.jpg',
    rating: 8.3,
    year: 2019,
    aiHint: 'teen comedy',
  },
  {
    id: '30',
    title: 'The Umbrella Academy',
    description: 'A family of former child heroes, now grown apart, must reunite to continue to protect the world.',
    genre: 'Action',
    cast: ['Elliot Page', 'Tom Hopper', 'David Castañeda'],
    posterUrl: 'https://image.tmdb.org/t/p/original/qJRB789ceLryrLvOKrZqLKr2CGf.jpg',
    rating: 8.0,
    year: 2019,
    aiHint: 'superhero action',
  },
  {
    id: '31',
    title: 'Lupin',
    description: 'Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.',
    genre: 'Crime',
    cast: ['Omar Sy', 'Ludivine Sagnier', 'Clotilde Hesme'],
    posterUrl: 'https://br.web.img2.acsta.net/c_310_420/pictures/20/12/02/16/22/0450183.jpg',
    rating: 7.5,
    year: 2021,
    aiHint: 'heist thriller',
  },
  {
    id: '32',
    title: 'Elite',
    description: 'When three working-class teens enroll in an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.',
    genre: 'Thriller',
    cast: ['Itzan Escamilla', 'Miguel Bernardeau', 'Arón Piper'],
    posterUrl: 'https://image.tmdb.org/t/p/original/3NTAbA93S4AbqaLdeOJ2pL3dY0p.jpg',
    rating: 7.5,
    year: 2018,
    aiHint: 'teen thriller',
  },
  {
    id: '33',
    title: 'Wednesday',
    description: 'While attending Nevermore Academy, Wednesday Addams attempts to master her emerging psychic ability, thwart a monstrous killing spree, and solve the supernatural mystery that embroiled her parents 25 years ago.',
    genre: 'Comedy',
    cast: ['Jenna Ortega', 'Gwendoline Christie', 'Riki Lindhome'],
    posterUrl: 'https://image.tmdb.org/t/p/original/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
    rating: 8.2,
    year: 2022,
    aiHint: 'dark comedy',
  },
  {
    id: '34',
    title: 'Dahmer – Monster: The Jeffrey Dahmer Story',
    description: 'Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?',
    genre: 'Crime',
    cast: ['Evan Peters', 'Richard Jenkins', 'Molly Ringwald'],
    posterUrl: 'https://image.tmdb.org/t/p/original/f2PVrOLygnPsOVqI2Oa4tC0A2a.jpg',
    rating: 8.1,
    year: 2022,
    aiHint: 'true crime',
  },
  {
    id: '35',
    title: 'The Sandman',
    description: 'Upon escaping after decades of imprisonment by a mortal wizard, Dream, the personification of dreams, sets about to reclaim his lost equipment.',
    genre: 'Fantasy',
    cast: ['Tom Sturridge', 'Boyd Holbrook', 'Patton Oswalt'],
    posterUrl: 'https://image.tmdb.org/t/p/original/q54qEgagGOYCq5D1903eBVMNkbo.jpg',
    rating: 7.8,
    year: 2022,
    aiHint: 'dark fantasy',
  },
  {
    id: '36',
    title: 'All of Us Are Dead',
    description: 'A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out - or turn into one of the rabid infected.',
    genre: 'Horror',
    cast: ['Park Ji-hu', 'Yoon Chan-young', 'Cho Yi-hyun'],
    posterUrl: 'https://image.tmdb.org/t/p/original/pTEFqAjLd5YTsMD6NS8AyVfI8aA.jpg',
    rating: 7.5,
    year: 2022,
    aiHint: 'zombie horror',
  },
  {
    id: '37',
    title: 'Lucifer',
    description: 'Lucifer Morningstar has decided he\'s had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity.',
    genre: 'Fantasy',
    cast: ['Tom Ellis', 'Lauren German', 'Kevin Alejandro'],
    posterUrl: 'https://image.tmdb.org/t/p/original/ekZobS8isE6mA53RAiGDG93hBxL.jpg',
    rating: 8.1,
    year: 2016,
    aiHint: 'urban fantasy',
  },
  {
    id: '38',
    title: 'Peaky Blinders',
    description: 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.',
    genre: 'Crime',
    cast: ['Cillian Murphy', 'Sam Neill', 'Helen McCrory'],
    posterUrl: 'https://image.tmdb.org/t/p/original/vUUqzSykdpkjvKyWiVAt2LgqI5s.jpg',
    rating: 8.8,
    year: 2013,
    aiHint: 'historical crime',
  },
  {
    id: '39',
    title: 'Vikings',
    description: 'The world of the Vikings is brought to life through the journey of Ragnar Lothbrok, the first Viking to emerge from Norse legend and onto the pages of history.',
    genre: 'History',
    cast: ['Travis Fimmel', 'Katheryn Winnick', 'Clive Standen'],
    posterUrl: 'https://image.tmdb.org/t/p/original/bQLrHIRNEkE3PdIWQrIAnXg9z3i.jpg',
    rating: 8.5,
    year: 2013,
    aiHint: 'historical drama',
  },
  {
    id: '40',
    title: 'The Last Kingdom',
    description: 'The year is 872, and many of the separate kingdoms of what we now know as England have fallen to the invading Danes, leaving the great kingdom of Wessex standing alone and defiant under the command of King Alfred.',
    genre: 'History',
    cast: ['Alexander Dreymon', 'Eliza Butterworth', 'Arnas Fedaravicius'],
    posterUrl: 'https://image.tmdb.org/t/p/original/8eJf0h0lG2A7H6J2Wp0kM52p2sC.jpg',
    rating: 8.4,
    year: 2015,
    aiHint: 'historical action',
  },
  {
    id: '41',
    title: 'The Haunting of Hill House',
    description: 'Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.',
    genre: 'Horror',
    cast: ['Victoria Pedretti', 'Oliver Jackson-Cohen', 'Henry Thomas'],
    posterUrl: 'https://image.tmdb.org/t/p/original/hLHeK09dls5jK25w4aY0Hld2u6M.jpg',
    rating: 8.6,
    year: 2018,
    aiHint: 'supernatural horror',
  },
  {
    id: '42',
    title: 'Mindhunter',
    description: 'Set in the late 1970s, two FBI agents are tasked with interviewing serial killers to solve open cases.',
    genre: 'Crime',
    cast: ['Jonathan Groff', 'Holt McCallany', 'Anna Torv'],
    posterUrl: 'https://image.tmdb.org/t/p/original/fbKE87mojpIETWepSbD5d3aVFAb.jpg',
    rating: 8.6,
    year: 2017,
    aiHint: 'psychological thriller',
  },
  {
    id: '43',
    title: 'Russian Doll',
    description: 'A cynical young woman in New York City keeps dying and returning to the party that\'s being thrown in her honor on that same evening.',
    genre: 'Comedy',
    cast: ['Natasha Lyonne', 'Charlie Barnett', 'Greta Lee'],
    posterUrl: 'https://image.tmdb.org/t/p/original/s4m34TzkR2S2UGyBmgKj2n7Iu0k.jpg',
    rating: 7.8,
    year: 2019,
    aiHint: 'comedy drama',
  },
  {
    id: '44',
    title: 'Glow',
    description: 'A look at the personal and professional lives of a group of women who perform for a wrestling organization in 1980s Los Angeles.',
    genre: 'Comedy',
    cast: ['Alison Brie', 'Betty Gilpin', 'Marc Maron'],
    posterUrl: 'https://image.tmdb.org/t/p/original/4BfV1Bwa1b679asb6i2Q3y3s21a.jpg',
    rating: 8.0,
    year: 2017,
    aiHint: 'wrestling comedy',
  },
  {
    id: '45',
    title: 'Unbelievable',
    description: 'Based on the true story of Marie, a teenager who was charged with lying about having been raped, and the two female detectives who followed a twisting path to arrive at the truth.',
    genre: 'Crime',
    cast: ['Kaitlyn Dever', 'Toni Collette', 'Merritt Wever'],
    posterUrl: 'https://image.tmdb.org/t/p/original/zZ3C1eb9t3hGv0KAfL3iC5aB6s6.jpg',
    rating: 8.4,
    year: 2019,
    aiHint: 'true crime',
  },
  {
    id: '46',
    title: 'When They See Us',
    description: 'Five teens from Harlem become trapped in a nightmare when they\'re falsely accused of a brutal attack in Central Park.',
    genre: 'Drama',
    cast: ['Jharrel Jerome', 'Asante Blackk', 'Caleel Harris'],
    posterUrl: 'https://image.tmdb.org/t/p/original/A22SAiJKs34o3aFBmubDBAui34.jpg',
    rating: 8.9,
    year: 2019,
    aiHint: 'biographical drama',
  },
  {
    id: '47',
    title: 'Maid',
    description: 'After fleeing an abusive relationship, a young mother finds a job cleaning houses as she fights to provide for her child and build them a better future.',
    genre: 'Drama',
    cast: ['Margaret Qualley', 'Nick Robinson', 'Andie MacDowell'],
    posterUrl: 'https://image.tmdb.org/t/p/original/p5hN0Vb2fhD5T5F3v58pB5a2s1j.jpg',
    rating: 8.4,
    year: 2021,
    aiHint: 'drama series',
  },
  {
    id: '48',
    title: 'Tiger King',
    description: 'A rivalry between big cat eccentrics takes a dark turn when Joe Exotic, a controversial animal park boss, is caught in a murder-for-hire plot.',
    genre: 'Documentary',
    cast: ['Joe Exotic', 'Carole Baskin', 'Doc Antle'],
    posterUrl: 'https://image.tmdb.org/t/p/original/pmh5J323h6M534d4y2jHlZkG7V.jpg',
    rating: 7.5,
    year: 2020,
    aiHint: 'true crime',
  },
  {
    id: '49',
    title: 'Making a Murderer',
    description: 'Filmed over a 10-year period, this real-life thriller follows the unprecedented story of two men accused of a grisly crime they may not have committed.',
    genre: 'Documentary',
    cast: ['Steven Avery', 'Brendan Dassey', 'Dolores Avery'],
    posterUrl: 'https://image.tmdb.org/t/p/original/8aVpCASp20j4nJFE5f8IEMaE6q0.jpg',
    rating: 8.6,
    year: 2015,
    aiHint: 'crime documentary',
  },
  {
    id: '50',
    title: 'Cheer',
    description: 'In the small town of Corsicana, Texas, a hard-driving head cheer coach demands perfection from her squad of competitive college athletes.',
    genre: 'Documentary',
    cast: ['Monica Aldama', 'Gabi Butler', 'Lexi Brumback'],
    posterUrl: 'https://image.tmdb.org/t/p/original/u2GhGDBY4ptjnxT5mcb6w3D2bzl.jpg',
    rating: 8.1,
    year: 2020,
    aiHint: 'sports documentary',
  },
  {
    id: '51',
    title: 'Formula 1: Drive to Survive',
    description: 'Docuseries following the FIA Formula One World Championship across multiple seasons.',
    genre: 'Documentary',
    cast: ['Will Buxton', 'Lewis Hamilton', 'Max Verstappen'],
    posterUrl: 'https://image.tmdb.org/t/p/original/gNqEV30s8n2y7aLp4pE4f6fPngm.jpg',
    rating: 8.6,
    year: 2019,
    aiHint: 'sports documentary',
  },
  {
    id: '52',
    title: 'The Great British Baking Show',
    description: 'Bakers attempt three challenges each week trying to impress the judges, with one being eliminated each week.',
    genre: 'Reality-TV',
    cast: ['Paul Hollywood', 'Prue Leith', 'Noel Fielding'],
    posterUrl: 'https://image.tmdb.org/t/p/original/539EmnlR5j25Ah3cia2a04XJ53M.jpg',
    rating: 8.6,
    year: 2010,
    aiHint: 'baking competition',
  },
  {
    id: '53',
    title: 'Queer Eye',
    description: 'A new Fab Five set out to Atlanta to help the city\'s straight men refine their wardrobes, grooming, diet, cultural pursuits, and home décor.',
    genre: 'Reality-TV',
    cast: ['Antoni Porowski', 'Tan France', 'Karamo Brown'],
    posterUrl: 'https://image.tmdb.org/t/p/original/5c22TCj6B3p87s1eMAnQe3z1k9H.jpg',
    rating: 8.5,
    year: 2018,
    aiHint: 'makeover reality',
  },
  {
    id: '54',
    title: 'Love is Blind',
    description: 'Singles who want to be loved for who they are, not what they look like, have signed up for a less conventional approach to modern dating.',
    genre: 'Reality-TV',
    cast: ['Nick Lachey', 'Vanessa Lachey', ''],
    posterUrl: 'https://image.tmdb.org/t/p/original/hC4A8S1k1F9nJyA8NfGatT66jG.jpg',
    rating: 6.0,
    year: 2020,
    aiHint: 'dating show',
  },
  {
    id: '55',
    title: 'Selling Sunset',
    description: 'The elite real estate brokers at The Oppenheim Group sell the luxe life to affluent buyers in LA. The drama ramps up when a new agent joins the team.',
    genre: 'Reality-TV',
    cast: ['Chrishell Stause', 'Christine Quinn', 'Mary Fitzgerald'],
    posterUrl: 'https://image.tmdb.org/t/p/original/s2aX1h0eXj4nS0Bsm4f21G2TG5.jpg',
    rating: 6.4,
    year: 2019,
    aiHint: 'real estate',
  },
  {
    id: '56',
    title: 'Too Hot to Handle',
    description: 'On the shores of paradise, gorgeous singles meet and mingle. But there\'s a twist. To win a $100,000 grand prize, they\'ll have to give up sex.',
    genre: 'Reality-TV',
    cast: ['Desiree Burch', '', ''],
    posterUrl: 'https://image.tmdb.org/t/p/original/pApsP4P0m3Oq2QkyfHk1WacK62f.jpg',
    rating: 4.6,
    year: 2020,
    aiHint: 'dating reality',
  },
  {
    id: '57',
    title: 'The Circle',
    description: 'A social experiment and competition show where online players flirt, befriend and catfish their way toward $100,000.',
    genre: 'Reality-TV',
    cast: ['Michelle Buteau', '', ''],
    posterUrl: 'https://image.tmdb.org/t/p/original/fQe02Gl4hN25b9mGpyN90K8iH4i.jpg',
    rating: 7.3,
    year: 2020,
    aiHint: 'social experiment',
  },
  {
    id: '58',
    title: 'Master of None',
    description: 'The personal and professional life of Dev, a 30-year-old actor in New York.',
    genre: 'Comedy',
    cast: ['Aziz Ansari', 'Eric Wareheim', 'Lena Waithe'],
    posterUrl: 'https://image.tmdb.org/t/p/original/v98v5CrW1tW2s9Ld2yA3VDIHPA.jpg',
    rating: 8.2,
    year: 2015,
    aiHint: 'comedy drama',
  },
  {
    id: '59',
    title: 'Unbreakable Kimmy Schmidt',
    description: 'A woman is rescued from a doomsday cult and starts life over again in New York City.',
    genre: 'Comedy',
    cast: ['Ellie Kemper', 'Jane Krakowski', 'Tituss Burgess'],
    posterUrl: 'https://image.tmdb.org/t/p/original/gFVYkF1bV3GytBOSu2vFsoT802N.jpg',
    rating: 7.6,
    year: 2015,
    aiHint: 'sitcom comedy',
  },
  {
    id: '60',
    title: 'BoJack Horseman',
    description: 'Meet the most beloved sitcom horse of the \'90s - 20 years later. BoJack Horseman was the star of the hit TV show "Horsin\' Around," but today he\'s washed up, living in Hollywood, complaining about everything, and wearing colorful sweaters.',
    genre: 'Animation',
    cast: ['Will Arnett', 'Amy Sedaris', 'Alison Brie'],
    posterUrl: 'https://image.tmdb.org/t/p/original/pB9L1Gk02w5I3s0bB4i32s42a3.jpg',
    rating: 8.7,
    year: 2014,
    aiHint: 'adult animation',
  },
  {
    id: '61',
    title: 'Big Mouth',
    description: 'Teenage friends find their lives upended by the wonders and horrors of puberty.',
    genre: 'Animation',
    cast: ['Nick Kroll', 'John Mulaney', 'Jessi Klein'],
    posterUrl: 'https://image.tmdb.org/t/p/original/hCBLb21s5xgy3nK34v4WU14AAp.jpg',
    rating: 8.0,
    year: 2017,
    aiHint: 'animated comedy',
  },
  {
    id: '62',
    title: 'Castlevania',
    description: 'A vampire hunter fights to save a besieged city from an army of otherworldly beasts controlled by Dracula himself.',
    genre: 'Animation',
    cast: ['Richard Armitage', 'James Callis', 'Alejandra Reynoso'],
    posterUrl: 'https://image.tmdb.org/t/p/original/lqf1h1Tpp5hdI2tSR2C944c667n.jpg',
    rating: 8.3,
    year: 2017,
    aiHint: 'dark fantasy',
  },
  {
    id: '63',
    title: 'Arcane',
    description: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
    genre: 'Animation',
    cast: ['Hailee Steinfeld', 'Katie Leung', 'Kevin Alejandro'],
    posterUrl: 'https://image.tmdb.org/t/p/original/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    rating: 9.0,
    year: 2021,
    aiHint: 'steampunk fantasy',
  },
  {
    id: '64',
    title: 'Cyberpunk: Edgerunners',
    description: 'A Street Kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an Edgerunner - a mercenary outlaw also known as a cyberpunk.',
    genre: 'Animation',
    cast: ['Zach Aguilar', 'Emi Lo', 'William C. Stephens'],
    posterUrl: 'https://image.tmdb.org/t/p/original/7t3f1QJy02hNhX2f3vw55nCgU78.jpg',
    rating: 8.6,
    year: 2022,
    aiHint: 'cyberpunk anime',
  },
  {
    id: '65',
    title: 'Altered Carbon',
    description: 'Set in a future where consciousness is digitized and stored, a prisoner returns to life in a new body and must solve a mind-bending murder to win his freedom.',
    genre: 'Sci-Fi',
    cast: ['Joel Kinnaman', 'James Purefoy', 'Martha Higareda'],
    posterUrl: 'https://image.tmdb.org/t/p/original/d5w2Aq2p4Z1B9iIZv4g2rJ83UX.jpg',
    rating: 8.0,
    year: 2018,
    aiHint: 'cyberpunk mystery',
  },
  {
    id: '66',
    title: 'House of Cards',
    description: 'A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.',
    genre: 'Drama',
    cast: ['Kevin Spacey', 'Robin Wright', 'Michael Kelly'],
    posterUrl: 'https://image.tmdb.org/t/p/original/hU3bD2NS1MYr9BysyJ4fOfaI4qS.jpg',
    rating: 8.7,
    year: 2013,
    aiHint: 'political drama',
  },
  {
    id: '67',
    title: 'Orange Is the New Black',
    description: 'Convicted of a decade old crime of transporting drug money to an ex-girlfriend, normally law-abiding Piper Chapman is sentenced to a year and a half behind bars.',
    genre: 'Comedy',
    cast: ['Taylor Schilling', 'Danielle Brooks', 'Taryn Manning'],
    posterUrl: 'https://image.tmdb.org/t/p/original/zF3f6P5sxxF5S8t45QXB32wOve.jpg',
    rating: 8.0,
    year: 2013,
    aiHint: 'prison drama',
  },
  {
    id: '68',
    title: '13 Reasons Why',
    description: 'Follows teenager Clay Jensen, in his quest to uncover the story behind his classmate and crush, Hannah, and her decision to end her life.',
    genre: 'Drama',
    cast: ['Dylan Minnette', 'Katherine Langford', 'Christian Navarro'],
    posterUrl: 'https://image.tmdb.org/t/p/original/pLg3e602n24T4aTqAnmDV2T6aY8.jpg',
    rating: 7.5,
    year: 2017,
    aiHint: 'teen drama',
  },
  {
    id: '69',
    title: 'Atypical',
    description: 'Sam, an 18-year-old on the autism spectrum, decides it\'s time to find a girlfriend, a journey that sets Sam\'s mom on her own life-changing path as her son seeks more independence.',
    genre: 'Comedy',
    cast: ['Keir Gilchrist', 'Jennifer Jason Leigh', 'Michael Rapaport'],
    posterUrl: 'https://image.tmdb.org/t/p/original/jBf2BEOxYv2hC0A4fXrtfLdM09.jpg',
    rating: 8.3,
    year: 2017,
    aiHint: 'coming of age',
  },
  {
    id: '70',
    title: 'Dead to Me',
    description: 'A hotheaded widow searching for the hit-and-run driver who mowed down her husband befriends an eccentric optimist who isn\'t quite what she seems.',
    genre: 'Comedy',
    cast: ['Christina Applegate', 'Linda Cardellini', 'James Marsden'],
    posterUrl: 'https://image.tmdb.org/t/p/original/r09mABJ1pMVpABp2eEBCa38bU3G.jpg',
    rating: 8.0,
    year: 2019,
    aiHint: 'dark comedy',
  },
  {
    id: '71',
    title: 'The Good Place',
    description: 'Four people and their otherworldly frienemy struggle in the afterlife to define what it means to be good.',
    genre: 'Comedy',
    cast: ['Kristen Bell', 'Ted Danson', 'William Jackson Harper'],
    posterUrl: 'https://image.tmdb.org/t/p/original/eIcj8sKTa1iUX2yWw22QyYC2jR.jpg',
    rating: 8.2,
    year: 2016,
    aiHint: 'fantasy comedy',
  },
  {
    id: '72',
    title: 'Never Have I Ever',
    description: 'The complicated life of a modern-day first-generation Indian American teenage girl, inspired by Mindy Kaling\'s own childhood.',
    genre: 'Comedy',
    cast: ['Maitreyi Ramakrishnan', 'Poorna Jagannathan', 'Darren Barnet'],
    posterUrl: 'https://image.tmdb.org/t/p/original/32n7dVIrK3eQyS25b73q0vj0c5F.jpg',
    rating: 7.9,
    year: 2020,
    aiHint: 'teen comedy',
  },
  {
    id: '73',
    title: 'Emily in Paris',
    description: 'A young American woman from the Midwest is hired by a marketing firm in Paris to provide them with an American perspective on things.',
    genre: 'Comedy',
    cast: ['Lily Collins', 'Philippine Leroy-Beaulieu', 'Ashley Park'],
    posterUrl: 'https://image.tmdb.org/t/p/original/Ars2h9o2A1l68d9w4w3x2p9wQ5.jpg',
    rating: 6.9,
    year: 2020,
    aiHint: 'rom com',
  },
  {
    id: '74',
    title: 'Money Heist: Korea – Joint Economic Area',
    description: 'Thieves overtake the mint of a unified Korea. With hostages trapped inside, the police must stop them — as well as the shadowy mastermind behind it all.',
    genre: 'Crime',
    cast: ['Yoo Ji-tae', 'Park Hae-soo', 'Jeon Jong-seo'],
    posterUrl: 'https://image.tmdb.org/t/p/original/24ifvJyhHjXGzI9oWqJ3oUv323.jpg',
    rating: 6.3,
    year: 2022,
    aiHint: 'heist action',
  },
  {
    id: '75',
    title: 'Sweet Home',
    description: 'As humans turn into savage monsters and wreak terror, one troubled teen and his apartment neighbors fight to survive — and to hold on to their humanity.',
    genre: 'Horror',
    cast: ['Song Kang', 'Lee Jin-wook', 'Lee Si-young'],
    posterUrl: 'https://image.tmdb.org/t/p/original/eAbq855j0D626yIay08QL7SPo7.jpg',
    rating: 7.4,
    year: 2020,
    aiHint: 'monster horror',
  },
  {
    id: '76',
    title: 'Kingdom',
    description: 'While strange rumors about their ill King grip a kingdom, the crown prince becomes their only hope against a mysterious plague overtaking the land.',
    genre: 'Horror',
    cast: ['Ju Ji-hoon', 'Ryu Seung-ryong', 'Bae Doona'],
    posterUrl: 'https://image.tmdb.org/t/p/original/3pDmRjK5s02OONc2Nusl2t33aJn.jpg',
    rating: 8.4,
    year: 2019,
    aiHint: 'historical horror',
  },
  {
    id: '77',
    title: 'Sense8',
    description: 'A group of people around the world are suddenly linked mentally, and must find a way to survive being hunted by those who see them as a threat to the world\'s order.',
    genre: 'Sci-Fi',
    cast: ['Doona Bae', 'Jamie Clayton', 'Tina Desai'],
    posterUrl: 'https://image.tmdb.org/t/p/original/fSgUuLPJ7hOaB21bCbtA13v2HAC.jpg',
    rating: 8.2,
    year: 2015,
    aiHint: 'sci-fi drama',
  },
  {
    id: '78',
    title: 'Grace and Frankie',
    description: 'Finding out that their husbands are not just work partners, but have also been romantically involved for the last twenty years, two women with an already strained relationship try to cope with the circumstances together.',
    genre: 'Comedy',
    cast: ['Jane Fonda', 'Lily Tomlin', 'Sam Waterston'],
    posterUrl: 'https://image.tmdb.org/t/p/original/tO3Fjw1oKx4aR6j9pfsD0aM67c.jpg',
    rating: 8.2,
    year: 2015,
    aiHint: 'sitcom comedy',
  },
  {
    id: '79',
    title: 'Travelers',
    description: 'A federal agent tracks four people who suddenly seem to possess entirely new personalities, leading to a startling discovery about humanity\'s future.',
    genre: 'Sci-Fi',
    cast: ['Eric McCormack', 'MacKenzie Porter', 'Nesta Cooper'],
    posterUrl: 'https://image.tmdb.org/t/p/original/a0ymwxbqEDnBvY1bBvMfh26m88a.jpg',
    rating: 8.1,
    year: 2016,
    aiHint: 'time travel',
  },
  {
    id: '80',
    title: 'The OA',
    description: 'Having gone missing seven years ago, the previously blind Prairie Johnson returns home, now in her late 20s with her sight restored. While many believe she is a miracle, others worry that she could be dangerous.',
    genre: 'Drama',
    cast: ['Brit Marling', 'Jason Isaacs', 'Scott Wilson'],
    posterUrl: 'https://image.tmdb.org/t/p/original/p4313sy6eLNZ0sS66nSgLdKL41a.jpg',
    rating: 7.8,
    year: 2016,
    aiHint: 'mystery drama',
  },
  {
    id: '81',
    title: 'Jessica Jones',
    description: 'Following a tragic end to her brief superhero career, Jessica Jones tries to rebuild her life as a private investigator, dealing with cases involving people with remarkable abilities in New York City.',
    genre: 'Action',
    cast: ['Krysten Ritter', 'Rachael Taylor', 'Eka Darville'],
    posterUrl: 'https://image.tmdb.org/t/p/original/lwL51y62tI2dM2Toa2Ea1eA6a0Q.jpg',
    rating: 7.9,
    year: 2015,
    aiHint: 'superhero noir',
  },
  {
    id: '82',
    title: 'Daredevil',
    description: 'A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.',
    genre: 'Action',
    cast: ['Charlie Cox', 'Vincent D\'Onofrio', 'Deborah Ann Woll'],
    posterUrl: 'https://image.tmdb.org/t/p/original/QWbPaD2G3Rj27n8ok6rA77sRz6G.jpg',
    rating: 8.6,
    year: 2015,
    aiHint: 'crime action',
  },
  {
    id: '83',
    title: 'The Punisher',
    description: 'After the murder of his family, Marine veteran Frank Castle becomes the vigilante known as "The Punisher," with only one goal in mind: to avenge them.',
    genre: 'Action',
    cast: ['Jon Bernthal', 'Amber Rose Revah', 'Ben Barnes'],
    posterUrl: 'https://image.tmdb.org/t/p/original/n2V2d3sA4D30onB6xhDli7A03aP.jpg',
    rating: 8.5,
    year: 2017,
    aiHint: 'vigilante action',
  },
  {
    id: '84',
    title: 'Luke Cage',
    description: 'When a sabotaged experiment gives him super strength and unbreakable skin, Luke Cage becomes a fugitive attempting to rebuild his life in Harlem and must soon confront his past and fight a battle for the heart of his city.',
    genre: 'Action',
    cast: ['Mike Colter', 'Simone Missick', 'Theo Rossi'],
    posterUrl: 'https://image.tmdb.org/t/p/original/4Y3RNZa7vYg94O4P0NWeVnKxtBe.jpg',
    rating: 7.3,
    year: 2016,
    aiHint: 'superhero action',
  },
  {
    id: '85',
    title: 'Iron Fist',
    description: 'A young man is bestowed with incredible martial arts skills and a mystical force known as the Iron Fist.',
    genre: 'Action',
    cast: ['Finn Jones', 'Jessica Henwick', 'Tom Pelphrey'],
    posterUrl: 'https://image.tmdb.org/t/p/original/4l656m2g2uLKeaJcQEHvo44y62n.jpg',
    rating: 6.4,
    year: 2017,
    aiHint: 'martial arts',
  },
  {
    id: '86',
    title: 'The Defenders',
    description: 'Daredevil, Jessica Jones, Luke Cage, and Iron Fist team up to fight crime in New York City.',
    genre: 'Action',
    cast: ['Charlie Cox', 'Krysten Ritter', 'Mike Colter'],
    posterUrl: 'https://image.tmdb.org/t/p/original/49S2N6pSct9a8vFMv44Gge2aYlH.jpg',
    rating: 7.2,
    year: 2017,
    aiHint: 'superhero team',
  },
  {
    id: '87',
    title: 'Santa Clarita Diet',
    description: 'Sheila and Joel are real estate agents in Santa Clarita, California. When Sheila dies, their lives take a dark turn.',
    genre: 'Comedy',
    cast: ['Drew Barrymore', 'Timothy Olyphant', 'Liv Hewson'],
    posterUrl: 'https://image.tmdb.org/t/p/original/pA11pxG4KmVmG2DqDB3x1gMAIO.jpg',
    rating: 7.8,
    year: 2017,
    aiHint: 'horror comedy',
  },
  {
    id: '88',
    title: 'American Vandal',
    description: 'A true-crime satire that explores the aftermath of a costly high school prank that left twenty-seven faculty cars vandalized with phallic images.',
    genre: 'Comedy',
    cast: ['Tyler Alvarez', 'Griffin Gluck', 'Jimmy Tatro'],
    posterUrl: 'https://image.tmdb.org/t/p/original/jF3pcLEgJa4cI2a1j4z3a2x3iY.jpg',
    rating: 8.2,
    year: 2017,
    aiHint: 'mockumentary comedy',
  },
  {
    id: '89',
    title: 'F is for Family',
    description: 'Follow the Murphy family back to the 1970s, when kids roamed wild, beer flowed freely and nothing came between a man and his TV.',
    genre: 'Animation',
    cast: ['Bill Burr', 'Laura Dern', 'Justin Long'],
    posterUrl: 'https://image.tmdb.org/t/p/original/fLhh3gC4u9E6s2sBvP8aCajpM5.jpg',
    rating: 8.0,
    year: 2015,
    aiHint: 'adult animation',
  },
  {
    id: '90',
    title: 'I Think You Should Leave with Tim Robinson',
    description: 'A sketch-comedy series where the host and guests say and do things that are so bizarre, you can\'t help but laugh.',
    genre: 'Comedy',
    cast: ['Tim Robinson', 'Sam Richardson', 'Patti Harrison'],
    posterUrl: 'https://image.tmdb.org/t/p/original/s4fV2wsXRW6A02p3g2x1Lp0vubw.jpg',
    rating: 8.0,
    year: 2019,
    aiHint: 'sketch comedy',
  },
  {
    id: '91',
    title: 'Midnight Mass',
    description: 'The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe.',
    genre: 'Horror',
    cast: ['Kate Siegel', 'Zach Gilford', 'Hamish Linklater'],
    posterUrl: 'https://image.tmdb.org/t/p/original/98fA4gG1a0x6nkk6nGSb7A2L8S.jpg',
    rating: 7.7,
    year: 2021,
    aiHint: 'supernatural horror',
  },
  {
    id: '92',
    title: 'The Midnight Club',
    description: 'At a manor with a mysterious history, the 8 members of the Midnight Club meet each night at midnight to tell sinister stories – and to look for signs of the supernatural from the beyond.',
    genre: 'Horror',
    cast: ['Iman Benson', 'Igby Rigney', 'Ruth Codd'],
    posterUrl: 'https://image.tmdb.org/t/p/original/1D4U2x5iW8g5Gg24N3sKz5Y42Q.jpg',
    rating: 6.6,
    year: 2022,
    aiHint: 'teen horror',
  },
  {
    id: '93',
    title: 'The Fall of the House of Usher',
    description: 'To secure their fortune — and future — two ruthless siblings build a family dynasty that begins to crumble when their heirs mysteriously die, one by one.',
    genre: 'Horror',
    cast: ['Carla Gugino', 'Bruce Greenwood', 'Mary McDonnell'],
    posterUrl: 'https://image.tmdb.org/t/p/original/jwu6T2in5Kq942H39l3z4iRaddc.jpg',
    rating: 8.0,
    year: 2023,
    aiHint: 'gothic horror',
  },
  {
    id: '94',
    title: 'Beef',
    description: 'A road rage incident between two strangers — a failing contractor and an unfulfilled entrepreneur — sparks a feud that brings out their darkest impulses.',
    genre: 'Comedy',
    cast: ['Steven Yeun', 'Ali Wong', 'Joseph Lee'],
    posterUrl: 'https://image.tmdb.org/t/p/original/2OFSG3jRxxd811VpgkSgX6SgC5r.jpg',
    rating: 8.0,
    year: 2023,
    aiHint: 'dark comedy',
  },
  {
    id: '95',
    title: 'One Piece',
    description: 'In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as \'One Piece.\'',
    genre: 'Action',
    cast: ['Iñaki Godoy', 'Mackenyu', 'Emily Rudd'],
    posterUrl: 'https://image.tmdb.org/t/p/original/w25PT2nBDCHIN3l2ws9i5Tz4gI.jpg',
    rating: 8.4,
    year: 2023,
    aiHint: 'fantasy adventure',
  },
  {
    id: '96',
    title: 'Avatar: The Last Airbender',
    description: 'A young boy known as the Avatar must master the four elemental powers to save a world at war — and fight a ruthless enemy bent on stopping him.',
    genre: 'Action',
    cast: ['Gordon Cormier', 'Kiawentiio', 'Ian Ousley'],
    posterUrl: 'https://image.tmdb.org/t/p/original/2mMYq6y0vKkj9c3I49j1aT7c21O.jpg',
    rating: 7.3,
    year: 2024,
    aiHint: 'fantasy action',
  },
  {
    id: '97',
    title: '3 Body Problem',
    description: 'A fateful decision in 1960s China reverberates across space and time to a group of brilliant scientists in the present day. As the laws of nature unravel before their eyes, they must confront humanity\'s greatest threat.',
    genre: 'Sci-Fi',
    cast: ['Jess Hong', 'Liam Cunningham', 'Eiza González'],
    posterUrl: 'https://image.tmdb.org/t/p/original/3iF14e3z2xmu6srr2B3fLp2c78f.jpg',
    rating: 7.7,
    year: 2024,
    aiHint: 'sci-fi mystery',
  },
  {
    id: '98',
    title: 'The Diplomat',
    description: 'In the midst of an international crisis, a career diplomat lands in a high-profile job she’s unsuited for, with tectonic implications for her marriage and her political future.',
    genre: 'Drama',
    cast: ['Keri Russell', 'Rufus Sewell', 'David Gyasi'],
    posterUrl: 'https://image.tmdb.org/t/p/original/dC5nfe5RN2sCN2t263y50C92L4hd.jpg',
    rating: 8.0,
    year: 2023,
    aiHint: 'political thriller',
  },
  {
    id: '99',
    title: 'The Night Agent',
    description: 'A low-level FBI agent, working in the White House basement, mans a phone that never rings--until the night that it does, propelling him into a fast moving and dangerous conspiracy that ultimately leads all the way to the Oval Office.',
    genre: 'Action',
    cast: ['Gabriel Basso', 'Luciane Buchanan', 'Fola Evans-Akingbola'],
    posterUrl: 'https://image.tmdb.org/t/p/original/g5n0jsqSj2aKQC28IWA2zQd4F2h.jpg',
    rating: 7.5,
    year: 2023,
    aiHint: 'action thriller',
  },
  {
    id: '100',
    title: 'Heartstopper',
    description: 'Teens Charlie and Nick discover their unlikely friendship might be something more as they navigate school and young love in this coming-of-age series.',
    genre: 'Romance',
    cast: ['Kit Connor', 'Joe Locke', 'Yasmin Finney'],
    posterUrl: 'https://image.tmdb.org/t/p/original/fIu1nBGG349a31iG420JUCv4S1.jpg',
    rating: 8.7,
    year: 2022,
    aiHint: 'teen romance',
  }
];

    