
import type { Movie } from './types';

export const movies: Movie[] = [
  {
    id: '1',
    title: 'Dexter',
    description: 'A Miami forensics expert moonlights as a serial killer of other serial killers.',
    genre: 'Crime',
    cast: ['Michael C. Hall', 'Jennifer Carpenter', 'David Zayas'],
    posterUrl: 'https://m.media-amazon.com/images/I/81JKXT1j0OL._UF1000,1000_QL80_.jpg',
    rating: 8.6,
    year: 2006,
    aiHint: 'crime drama',
  },
  {
    id: '2',
    title: 'You',
    description: 'A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.',
    genre: 'Thriller',
    cast: ['Penn Badgley', 'Victoria Pedretti', 'Elizabeth Lail'],
    posterUrl: 'https://br.web.img3.acsta.net/pictures/18/12/31/02/49/2373131.jpg',
    rating: 7.7,
    year: 2018,
    aiHint: 'psychological thriller',
  },
  {
    id: '3',
    title: 'Outer Banks',
    description: 'On an island of haves and have-nots, teen John B enlists his three best friends to hunt for a legendary treasure linked to his father\'s disappearance.',
    genre: 'Action',
    cast: ['Chase Stokes', 'Madelyn Cline', 'Madison Bailey'],
    posterUrl: 'https://bds.tv.br/images/posters/18962.jpg',
    rating: 7.6,
    year: 2020,
    aiHint: 'teen adventure',
  },
  {
    id: '4',
    title: 'La Casa de Papel',
    description: 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.',
    genre: 'Thriller',
    cast: ['Úrsula Corberó', 'Álvaro Morte', 'Itziar Ituño'],
    posterUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRH78sjPMFTyIJE1M0s6T3bnszPjIfLmHkV4QqgvwLvYZIgJL_s',
    rating: 8.3,
    year: 2017,
    aiHint: 'heist thriller',
  },
  {
    id: '5',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    genre: 'Fantasy',
    cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcShwsh5DzMU6LwB72i0tI4RfVWmZXmfEiMfS-fpyGTsTJJvfhC4',
    rating: 8.8,
    year: 2001,
    aiHint: 'epic fantasy',
  },
  {
    id: '6',
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    genre: 'Crime',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
    rating: 8.9,
    year: 1994,
    aiHint: 'crime film',
  },
  {
    id: '7',
    title: 'Forrest Gump',
    description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
    genre: 'Drama',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    posterUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSOBbTE4n05v0bfz6rtuH67N3JGyWUYdh77lEi_oLZC4mPvqDPh',
    rating: 8.8,
    year: 1994,
    aiHint: 'life story',
  },
  {
    id: '8',
    title: 'Dark',
    description: 'A family saga with a supernatural twist, set in a German town, where the disappearance of two young children exposes the relationships among four families.',
    genre: 'Sci-Fi',
    cast: ['Louis Hofmann', 'Karoline Eichhorn', 'Lisa Vicari'],
    posterUrl: 'https://upload.wikimedia.org/wikipedia/pt/thumb/f/f6/Dark_%28s%C3%A9rie%29.jpg/250px-Dark_%28s%C3%A9rie%29.jpg',
    rating: 8.8,
    year: 2017,
    aiHint: 'mystery sci-fi',
  },
  {
    id: '9',
    title: 'Stranger Things',
    description: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
    genre: 'Sci-Fi',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR7RuFG1xNFUAjqIZMhhA5idmeXbLaNP9C5HbtrMaTGHiJa8H-',
    rating: 8.7,
    year: 2016,
    aiHint: 'supernatural horror',
  },
  {
    id: '10',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    genre: 'Crime',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSRQA5PMd_tejZuhUxk0S5JW7IWTmdKignL9gNsgZ_lHdt-IHrj',
    rating: 9.5,
    year: 2008,
    aiHint: 'crime drama',
  },
  {
    id: '11',
    title: 'Game of Thrones',
    description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    genre: 'Fantasy',
    cast: ['Emilia Clarke', 'Kit Harington', 'Peter Dinklage'],
    posterUrl: 'https://resizing.flixster.com/3ko6zO6791p1QPOXHUI2eCwmHXQ=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvMDIyOTBmN2QtMzM0Yi00ODUxLWE0MWYtMmViYWJiOGViZjRkLmpwZw==',
    rating: 9.2,
    year: 2011,
    aiHint: 'political fantasy',
  },
  {
    id: '12',
    title: 'The Office',
    description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    genre: 'Comedy',
    cast: ['Steve Carell', 'Rainn Wilson', 'John Krasinski'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaF-ubV-aP_3EjCWoIrCoLnRUhDlJsicdHuclKwrsy-IJMMztY',
    rating: 8.9,
    year: 2005,
    aiHint: 'workplace comedy',
  },
   {
    id: '13',
    title: 'Blade Runner 2049',
    description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
    genre: 'Sci-Fi',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST3dCSPLwz49qUGzsQlZAbDmOFuSAF_3e5uH-gvonfysREq7z0',
    rating: 8.0,
    year: 2017,
    aiHint: 'dystopian future'
  },
  {
    id: '14',
    title: 'Mad Max: Fury Road',
    description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    genre: 'Action',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH11eywQ4X9R_4Ucg1GAl4hz2zBM6WicS42tU3-ylALKQ9lxei',
    rating: 8.1,
    year: 2015,
    aiHint: 'post-apocalyptic action'
  },
  {
    id: '15',
    title: 'Spirited Away',
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    genre: 'Animation',
    cast: ['Daveigh Chase', 'Suzanne Pleshette', 'Miyu Irino'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRLMyA1BUde7-xBNDGkJRyHGVI1ITpVAuk7rZMYWLwOccEcGnuQ',
    rating: 8.6,
    year: 2001,
    aiHint: 'animated fantasy'
  },
  {
    id: '16',
    title: 'The Grand Budapest Hotel',
    description: 'The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.',
    genre: 'Comedy',
    cast: ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRjlgYXLE83x-Mg2cfmzZdSv9Ynyngr-v6EDz1Wswlb2UngUc--',
    rating: 8.1,
    year: 2014,
    aiHint: 'quirky comedy'
  },
  {
    id: '17',
    title: 'Black Mirror',
    description: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.',
    genre: 'Sci-Fi',
    cast: ['Jesse Plemons', 'Cristin Milioti', 'Jimmi Simpson'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjU0ZjZhNDQtMDhkYi00OWQyLWE3NGYtNzBlY2VmM2I4ZDg5XkEyXkFqcGc@._V1_.jpg',
    rating: 8.8,
    year: 2011,
    aiHint: 'tech anthology'
  },
  {
    id: '18',
    title: 'Fleabag',
    description: 'A comedy series adapted from the award-winning play about a young woman trying to cope with life in London whilst coming to terms with a recent tragedy.',
    genre: 'Comedy',
    cast: ['Phoebe Waller-Bridge', 'Sian Clifford', 'Olivia Colman'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQCCjCbok_8V1acA7zfThv2WfjilE41rTHG8VItqjZ9Uw6LP9Uy',
    rating: 8.7,
    year: 2016,
    aiHint: 'dark comedy'
  },
  {
    id: '19',
    title: 'Chernobyl',
    description: 'In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world\'s worst man-made catastrophes.',
    genre: 'Drama',
    cast: ['Jessie Buckley', 'Jared Harris', 'Stellan Skarsgård'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRcr0khV9t7IeOcVDRvC84eCW_5yidk-aWcf466252yFKNPAf5M',
    rating: 9.4,
    year: 2019,
    aiHint: 'historical drama'
  },
  {
    id: '20',
    title: 'The Social Network',
    description: 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by two brothers who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.',
    genre: 'Drama',
    cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
    posterUrl: 'https://www.europanet.com.br/image_gen/resizeimg.php?cod_produto=107066',
    rating: 7.7,
    year: 2010,
    aiHint: 'biographical drama'
  },
  {
    id: '21',
    title: 'The Witcher',
    description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
    genre: 'Fantasy',
    cast: ['Henry Cavill', 'Anya Chalotra', 'Freya Allan'],
    posterUrl: 'https://br.web.img3.acsta.net/pictures/19/11/29/17/57/5161763.jpg',
    rating: 8.2,
    year: 2019,
    aiHint: 'fantasy series',
  },
  {
    id: '22',
    title: 'Squid Game',
    description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    genre: 'Thriller',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9xtPB9p1KU15iD_zYBsrFGio_49GXOkyCfrh8Rgnngtzqk6fE',
    rating: 8.1,
    year: 2021,
    aiHint: 'survival drama',
  },
  {
    id: '23',
    title: 'Bridgerton',
    description: 'Wealth, lust, and betrayal set in the backdrop of Regency era England, seen through the eyes of the powerful Bridgerton family.',
    genre: 'Romance',
    cast: ['Phoebe Dynevor', 'Regé-Jean Page', 'Nicola Coughlan'],
    posterUrl: 'https://resizing.flixster.com/138uPFHeLeB8oGxrkUdCSHQDAsE=/fit-in/705x460/v2/https://resizing.flixster.com/I_zHuKCiZSwuXD7jSZ3WHpnVngo=/ems.cHJkLWVtcy1hc3NldHMvdHZzZXJpZXMvZjU3NzI1NTktNDBhNC00YTc4LThkZGYtODAxMTgwZmM3ZDlmLmpwZw==',
    rating: 7.3,
    year: 2020,
    aiHint: 'period romance',
  },
  {
    id: '24',
    title: 'The Crown',
    description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
    genre: 'Drama',
    cast: ['Claire Foy', 'Olivia Colman', 'Imelda Staunton'],
    posterUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWhRZawPRGIc6lo0jImRr1c722JcHYmHIEQKjThj4nqo33HZ6-',
    rating: 8.7,
    year: 2016,
    aiHint: 'historical drama',
  },
  {
    id: '25',
    title: 'The Queen\'s Gambit',
    description: 'Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA.',
    genre: 'Drama',
    cast: ['Anya Taylor-Joy', 'Bill Camp', 'Marielle Heller'],
    posterUrl: 'https://i.ebayimg.com/images/g/-8gAAOSw2E9i4bE3/s-l400.jpg',
    rating: 8.6,
    year: 2020,
    aiHint: 'chess drama',
  },
  {
    id: '26',
    title: 'Cobra Kai',
    description: 'Decades after their 1984 All Valley Karate Tournament bout, a middle-aged Daniel LaRusso and Johnny Lawrence find themselves martial-arts rivals again.',
    genre: 'Action',
    cast: ['Ralph Macchio', 'William Zabka', 'Xolo Maridueña'],
    posterUrl: 'https://br.web.img2.acsta.net/pictures/21/01/04/12/12/0170975.jpg',
    rating: 8.6,
    year: 2018,
    aiHint: 'karate action',
  },
  {
    id: '27',
    title: 'Sex Education',
    description: 'A teenage boy with a sex therapist mother teams up with a high school classmate to set up an underground sex therapy clinic at school.',
    genre: 'Comedy',
    cast: ['Asa Butterfield', 'Gillian Anderson', 'Ncuti Gatwa'],
    posterUrl: 'https://idris.com.br/dev/wp-content/uploads/2019/01/poltrona-Sex-education-poster.jpg',
    rating: 8.3,
    year: 2019,
    aiHint: 'teen comedy',
  },
  {
    id: '28',
    title: 'Ozark',
    description: 'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss.',
    genre: 'Crime',
    cast: ['Jason Bateman', 'Laura Linney', 'Julia Garner'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzMzMTM3ZWQtMWZhNS00N2RmLWE0YjUtYjA2MjY3NDM5ZWM0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: 8.4,
    year: 2017,
    aiHint: 'crime thriller',
  },
  {
    id: '29',
    title: 'Narcos',
    description: 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.',
    genre: 'Crime',
    cast: ['Wagner Moura', 'Boyd Holbrook', 'Pedro Pascal'],
    posterUrl: 'https://images.ctfassets.net/4cd45et68cgf/30ahhG9SI2h0qtMlIU8nXm/621568df5566b8f922239a8e94e2a0d2/EN-US_OPS1_Main_Illustrated_Vertical_27x40_RGB.jpg',
    rating: 8.8,
    year: 2015,
    aiHint: 'crime biopic',
  },
  {
    id: '30',
    title: 'The Umbrella Academy',
    description: 'A family of former child heroes, now grown apart, must reunite to continue to protect the world.',
    genre: 'Action',
    cast: ['Elliot Page', 'Tom Hopper', 'David Castañeda'],
    posterUrl: 'https://images.ctfassets.net/4cd45et68cgf/5ubPW3UKcPpDwThgu4X01O/7556b6756fcb6168b11caab885117e24/PT-BR_CARAMELO_Main-Key-Art_Dupla_Vertical_4x5_sRGB_PRE.jpg?w=2000',
    rating: 8.0,
    year: 2019,
    aiHint: 'superhero action',
  },
  {
    id: '31',
    title: 'Lupin',
    description: 'Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.',
    genre: 'Crime',
    cast: ['Omar Sy', 'Ludivine Sagnier', 'Clotilde Hesme'],
    posterUrl: 'https://resizing.flixster.com/i6Tzks6-0MJnC7fD7nrQx4pr9Rc=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vMmJkNzExNTItMWM0MS00ODBjLWJkNGMtMTIwMmI4YTc3YTg3LmpwZw==',
    rating: 7.5,
    year: 2021,
    aiHint: 'heist thriller',
  },
  {
    id: '32',
    title: 'Elite',
    description: 'When three working-class teens enroll in an exclusive private school in Spain, the clash between them and the wealthy students leads to murder.',
    genre: 'Thriller',
    cast: ['Itzan Escamilla', 'Miguel Bernardeau', 'Arón Piper'],
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BZTFkMDZkOWMtNDM3ZC00MWE0LTkxZWEtNjYyZTk4ODNiOTc4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    rating: 7.5,
    year: 2018,
    aiHint: 'teen thriller',
  },
  {
    id: '33',
    title: 'Wednesday',
    description: 'While attending Nevermore Academy, Wednesday Addams attempts to master her emerging psychic ability, thwart a monstrous killing spree, and solve the supernatural mystery that embroiled her parents 25 years ago.',
    genre: 'Comedy',
    cast: ['Jenna Ortega', 'Gwendoline Christie', 'Riki Lindhome'],
    posterUrl: 'https://image.tmdb.org/t/p/original/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
    rating: 8.2,
    year: 2022,
    aiHint: 'dark comedy',
  },
  {
    id: '34',
    title: 'Dahmer – Monster: The Jeffrey Dahmer Story',
    description: 'Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?',
    genre: 'Crime',
    cast: ['Evan Peters', 'Richard Jenkins', 'Molly Ringwald'],
    posterUrl: 'https://br.web.img3.acsta.net/pictures/18/05/22/19/39/4653775.jpg',
    rating: 8.1,
    year: 2022,
    aiHint: 'true crime',
  },
  {
    id: '35',
    title: 'The Sandman',
    description: 'Upon escaping after decades of imprisonment by a mortal wizard, Dream, the personification of dreams, sets about to reclaim his lost equipment.',
    genre: 'Fantasy',
    cast: ['Tom Sturridge', 'Boyd Holbrook', 'Patton Oswalt'],
    posterUrl: 'https://image.tmdb.org/t/p/original/q54qEgagGOYCq5D1903eBVMNkbo.jpg',
    rating: 7.8,
    year: 2022,
    aiHint: 'dark fantasy',
  },
  {
    id: '36',
    title: 'All of Us Are Dead',
    description: 'A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out - or turn into one of the rabid infected.',
    genre: 'Horror',
    cast: ['Park Ji-hu', 'Yoon Chan-young', 'Cho Yi-hyun'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTqM6ACcafVNdavplM3K0XUJ-BruTYT-zMCM8Xx4JRpYz1yMx8J',
    rating: 7.5,
    year: 2022,
    aiHint: 'zombie horror',
  },
  {
    id: '37',
    title: 'Lucifer',
    description: 'Lucifer Morningstar has decided he\'s had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity.',
    genre: 'Fantasy',
    cast: ['Tom Ellis', 'Lauren German', 'Kevin Alejandro'],
    posterUrl: 'https://image.tmdb.org/t/p/original/ekZobS8isE6mA53RAiGDG93hBxL.jpg',
    rating: 8.1,
    year: 2016,
    aiHint: 'urban fantasy',
  },
  {
    id: '38',
    title: 'Peaky Blinders',
    description: 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.',
    genre: 'Crime',
    cast: ['Cillian Murphy', 'Sam Neill', 'Helen McCrory'],
    posterUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTL3amOrwIItWCdXy-pSJPqrP-ui-L7By9LM2AasGDhC8THRDX6',
    rating: 8.8,
    year: 2013,
    aiHint: 'historical crime',
  },
  {
    id: '39',
    title: 'Vikings',
    description: 'The world of the Vikings is brought to life through the journey of Ragnar Lothbrok, the first Viking to emerge from Norse legend and onto the pages of history.',
    genre: 'History',
    cast: ['Travis Fimmel', 'Katheryn Winnick', 'Clive Standen'],
    posterUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSlpPU5wgtEAMIdbM3J6eQPdWuNRpnaZscjuCQiJeam_5EXB_yi',
    rating: 8.5,
    year: 2013,
    aiHint: 'historical drama',
  },
];

    